language: python

sudo: false

notifications:
    email: false
    
python:
  - 3.5

# Upgrade pip before install
before_install:
  - pip install -U pip

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - echo "Success!"
  
branches:
  only:
    - master
    
after_success:
  - pip install simple-lda
  - pip install charpy
  - pip install nprime
